"""initial schema

Revision ID: bde2610710e8
Revises: 
Create Date: 2026-05-08 22:16:07.044018
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bde2610710e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chains')),
    sa.UniqueConstraint('name', name=op.f('uq_chains_name'))
    )
    op.create_table('tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=96), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('is_stable', sa.Boolean(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk_tokens_chain_id_chains'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens')),
    sa.UniqueConstraint('chain_id', 'address', name='uq_tokens_chain_address')
    )
    op.create_index('ix_tokens_symbol', 'tokens', ['symbol'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=96), nullable=False),
    sa.Column('dex', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('token0_id', sa.BigInteger(), nullable=False),
    sa.Column('token1_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk_pools_chain_id_chains'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token0_id'], ['tokens.id'], name=op.f('fk_pools_token0_id_tokens'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['token1_id'], ['tokens.id'], name=op.f('fk_pools_token1_id_tokens'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pools')),
    sa.UniqueConstraint('chain_id', 'address', name='uq_pools_chain_address')
    )
    op.create_index('ix_pools_dex', 'pools', ['dex'], unique=False)
    op.create_index('ix_pools_first_seen_at', 'pools', ['first_seen_at'], unique=False)
    op.create_index('ix_pools_token0_token1', 'pools', ['token0_id', 'token1_id'], unique=False)
    op.create_table('universe_membership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_universe_membership_token_id_tokens'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_membership')),
    sa.UniqueConstraint('token_id', name='uq_universe_token')
    )
    op.create_index('ix_universe_tier', 'universe_membership', ['tier'], unique=False)
    op.create_table('liquidity_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('reserve0', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('reserve1', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('sqrt_price_x96', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('implied_price', sa.Float(), nullable=True),
    sa.Column('tvl_usd', sa.Float(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], name=op.f('fk_liquidity_snapshots_pool_id_pools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidity_snapshots'))
    )
    op.create_index('ix_liqsnap_pool_taken_at', 'liquidity_snapshots', ['pool_id', 'taken_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('base_token_id', sa.BigInteger(), nullable=True),
    sa.Column('quote_token_id', sa.BigInteger(), nullable=True),
    sa.Column('buy_pool_id', sa.BigInteger(), nullable=True),
    sa.Column('sell_pool_id', sa.BigInteger(), nullable=True),
    sa.Column('buy_chain_id', sa.Integer(), nullable=True),
    sa.Column('sell_chain_id', sa.Integer(), nullable=True),
    sa.Column('spread_bps', sa.Float(), nullable=True),
    sa.Column('notional_usd', sa.Float(), nullable=True),
    sa.Column('gross_profit_usd', sa.Float(), nullable=True),
    sa.Column('net_profit_usd', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 1', name=op.f('ck_opportunities_score_range')),
    sa.ForeignKeyConstraint(['base_token_id'], ['tokens.id'], name=op.f('fk_opportunities_base_token_id_tokens')),
    sa.ForeignKeyConstraint(['buy_chain_id'], ['chains.id'], name=op.f('fk_opportunities_buy_chain_id_chains')),
    sa.ForeignKeyConstraint(['buy_pool_id'], ['pools.id'], name=op.f('fk_opportunities_buy_pool_id_pools')),
    sa.ForeignKeyConstraint(['quote_token_id'], ['tokens.id'], name=op.f('fk_opportunities_quote_token_id_tokens')),
    sa.ForeignKeyConstraint(['sell_chain_id'], ['chains.id'], name=op.f('fk_opportunities_sell_chain_id_chains')),
    sa.ForeignKeyConstraint(['sell_pool_id'], ['pools.id'], name=op.f('fk_opportunities_sell_pool_id_pools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_fingerprint'), 'opportunities', ['fingerprint'], unique=False)
    op.create_index('ix_opps_kind_score_created', 'opportunities', ['kind', 'score', 'created_at'], unique=False)
    op.create_table('pool_states',
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('slot', sa.BigInteger(), nullable=True),
    sa.Column('reserve0', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('reserve1', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('sqrt_price_x96', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('tick', sa.Integer(), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('fee_growth_global0', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('fee_growth_global1', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('last_swap_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], name=op.f('fk_pool_states_pool_id_pools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool_id', name=op.f('pk_pool_states'))
    )
    op.create_table('suspicious_patterns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], name=op.f('fk_suspicious_patterns_pool_id_pools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suspicious_patterns'))
    )
    op.create_index(op.f('ix_suspicious_patterns_kind'), 'suspicious_patterns', ['kind'], unique=False)
    op.create_table('swaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.BigInteger(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=96), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('slot', sa.BigInteger(), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('sender', sa.String(length=96), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('amount0_in', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('amount1_in', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('amount0_out', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('amount1_out', sa.Numeric(precision=80, scale=0), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('usd_value', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], name=op.f('fk_swaps_chain_id_chains')),
    sa.ForeignKeyConstraint(['pool_id'], ['pools.id'], name=op.f('fk_swaps_pool_id_pools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_swaps'))
    )
    op.create_index(op.f('ix_swaps_observed_at'), 'swaps', ['observed_at'], unique=False)
    op.create_index('ix_swaps_pool_observed_at', 'swaps', ['pool_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_swaps_sender'), 'swaps', ['sender'], unique=False)
    op.create_index(op.f('ix_swaps_tx_hash'), 'swaps', ['tx_hash'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('opportunity_id', sa.BigInteger(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_alerts_opportunity_id_opportunities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('fingerprint', 'chat_id', name='uq_alerts_fingerprint_chat')
    )
    op.create_index('ix_alerts_sent_at', 'alerts', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_sent_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_swaps_tx_hash'), table_name='swaps')
    op.drop_index(op.f('ix_swaps_sender'), table_name='swaps')
    op.drop_index('ix_swaps_pool_observed_at', table_name='swaps')
    op.drop_index(op.f('ix_swaps_observed_at'), table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_suspicious_patterns_kind'), table_name='suspicious_patterns')
    op.drop_table('suspicious_patterns')
    op.drop_table('pool_states')
    op.drop_index('ix_opps_kind_score_created', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_fingerprint'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_liqsnap_pool_taken_at', table_name='liquidity_snapshots')
    op.drop_table('liquidity_snapshots')
    op.drop_index('ix_universe_tier', table_name='universe_membership')
    op.drop_table('universe_membership')
    op.drop_index('ix_pools_token0_token1', table_name='pools')
    op.drop_index('ix_pools_first_seen_at', table_name='pools')
    op.drop_index('ix_pools_dex', table_name='pools')
    op.drop_table('pools')
    op.drop_index('ix_tokens_symbol', table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('chains')
    # ### end Alembic commands ###
